"""empty message

Revision ID: 41dacf188a86
Revises: 
Create Date: 2023-06-22 13:37:05.677633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41dacf188a86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lost_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('choice_finder', sa.String(), nullable=True),
    sa.Column('track_num', sa.Integer(), nullable=True),
    sa.Column('notify', sa.Boolean(), nullable=True),
    sa.Column('get_item', sa.DateTime(), nullable=True),
    sa.Column('get_item_hour', sa.String(), nullable=True),
    sa.Column('get_item_minute', sa.String(), nullable=True),
    sa.Column('recep_item', sa.DateTime(), nullable=True),
    sa.Column('recep_item_hour', sa.String(), nullable=True),
    sa.Column('recep_item_minute', sa.String(), nullable=True),
    sa.Column('recep_manager', sa.String(), nullable=True),
    sa.Column('find_area', sa.String(), nullable=True),
    sa.Column('find_area_police', sa.String(), nullable=True),
    sa.Column('own_waiver', sa.String(), nullable=True),
    sa.Column('finder_name', sa.String(), nullable=True),
    sa.Column('own_name_note', sa.String(), nullable=True),
    sa.Column('finder_age', sa.Integer(), nullable=True),
    sa.Column('finder_sex', sa.String(), nullable=True),
    sa.Column('finder_post', sa.String(), nullable=True),
    sa.Column('finder_tel1', sa.String(), nullable=True),
    sa.Column('finder_tel2', sa.String(), nullable=True),
    sa.Column('item_class_L', sa.String(), nullable=True),
    sa.Column('item_class_M', sa.String(), nullable=True),
    sa.Column('item_class_S', sa.String(), nullable=True),
    sa.Column('item_value', sa.Boolean(), nullable=True),
    sa.Column('item_feature', sa.String(), nullable=True),
    sa.Column('item_color', sa.String(), nullable=True),
    sa.Column('item_storage', sa.String(), nullable=True),
    sa.Column('item_storage_place', sa.String(), nullable=True),
    sa.Column('item_maker', sa.String(), nullable=True),
    sa.Column('item_expiration', sa.DateTime(), nullable=True),
    sa.Column('item_num', sa.Integer(), nullable=True),
    sa.Column('item_unit', sa.String(), nullable=True),
    sa.Column('item_plice', sa.String(), nullable=True),
    sa.Column('item_money', sa.String(), nullable=True),
    sa.Column('item_remarks', sa.String(), nullable=True),
    sa.Column('item_situation', sa.Boolean(), nullable=True),
    sa.Column('finder_class', sa.String(), nullable=True),
    sa.Column('finder_affiliation', sa.String(), nullable=True),
    sa.Column('thirdparty_waiver', sa.String(), nullable=True),
    sa.Column('thirdparty_name_note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('lost_item')
    # ### end Alembic commands ###
