"""empty message

Revision ID: 908e439b1bf2
Revises: 
Create Date: 2023-08-04 21:33:47.215070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908e439b1bf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lost_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('choice_finder', sa.String(), nullable=True),
    sa.Column('track_num', sa.Integer(), nullable=True),
    sa.Column('notify', sa.Boolean(), nullable=True),
    sa.Column('get_item', sa.DateTime(), nullable=True),
    sa.Column('get_item_hour', sa.String(), nullable=True),
    sa.Column('get_item_minute', sa.String(), nullable=True),
    sa.Column('recep_item', sa.DateTime(), nullable=True),
    sa.Column('recep_item_hour', sa.String(), nullable=True),
    sa.Column('recep_item_minute', sa.String(), nullable=True),
    sa.Column('recep_manager', sa.String(), nullable=True),
    sa.Column('find_area', sa.String(), nullable=True),
    sa.Column('find_area_police', sa.String(), nullable=True),
    sa.Column('own_waiver', sa.String(), nullable=True),
    sa.Column('finder_name', sa.String(), nullable=True),
    sa.Column('own_name_note', sa.String(), nullable=True),
    sa.Column('finder_age', sa.Integer(), nullable=True),
    sa.Column('finder_sex', sa.String(), nullable=True),
    sa.Column('finder_post', sa.String(), nullable=True),
    sa.Column('finder_address', sa.String(), nullable=True),
    sa.Column('finder_tel1', sa.String(), nullable=True),
    sa.Column('finder_tel2', sa.String(), nullable=True),
    sa.Column('item_class_L', sa.String(), nullable=True),
    sa.Column('item_class_M', sa.String(), nullable=True),
    sa.Column('item_class_S', sa.String(), nullable=True),
    sa.Column('item_value', sa.Boolean(), nullable=True),
    sa.Column('item_feature', sa.String(), nullable=True),
    sa.Column('item_color', sa.String(), nullable=True),
    sa.Column('item_storage', sa.String(), nullable=True),
    sa.Column('item_storage_place', sa.String(), nullable=True),
    sa.Column('item_maker', sa.String(), nullable=True),
    sa.Column('item_expiration', sa.DateTime(), nullable=True),
    sa.Column('item_num', sa.Integer(), nullable=True),
    sa.Column('item_unit', sa.String(), nullable=True),
    sa.Column('item_plice', sa.String(), nullable=True),
    sa.Column('item_money', sa.String(), nullable=True),
    sa.Column('item_remarks', sa.String(), nullable=True),
    sa.Column('item_situation', sa.String(), nullable=True),
    sa.Column('item_image', sa.String(), nullable=True),
    sa.Column('finder_class', sa.String(), nullable=True),
    sa.Column('finder_affiliation', sa.String(), nullable=True),
    sa.Column('thirdparty_waiver', sa.String(), nullable=True),
    sa.Column('thirdparty_name_note', sa.String(), nullable=True),
    sa.Column('card_campany', sa.String(), nullable=True),
    sa.Column('card_tel', sa.String(), nullable=True),
    sa.Column('card_name', sa.String(), nullable=True),
    sa.Column('card_person', sa.String(), nullable=True),
    sa.Column('card_return', sa.DateTime(), nullable=True),
    sa.Column('card_item', sa.DateTime(), nullable=True),
    sa.Column('card_item_hour', sa.String(), nullable=True),
    sa.Column('card_item_minute', sa.String(), nullable=True),
    sa.Column('card_manager', sa.String(), nullable=True),
    sa.Column('lost_date', sa.DateTime(), nullable=True),
    sa.Column('lost_hour', sa.String(), nullable=True),
    sa.Column('lost_minute', sa.String(), nullable=True),
    sa.Column('lost_area', sa.String(), nullable=True),
    sa.Column('lost_person', sa.String(), nullable=True),
    sa.Column('lost_class', sa.String(), nullable=True),
    sa.Column('lost_affiliation', sa.String(), nullable=True),
    sa.Column('lost_tel1', sa.String(), nullable=True),
    sa.Column('lost_tel2', sa.String(), nullable=True),
    sa.Column('lost_post', sa.String(), nullable=True),
    sa.Column('lost_address', sa.String(), nullable=True),
    sa.Column('note_date', sa.DateTime(), nullable=True),
    sa.Column('note_hour', sa.String(), nullable=True),
    sa.Column('note_minute', sa.String(), nullable=True),
    sa.Column('note_process', sa.String(), nullable=True),
    sa.Column('note_manager', sa.String(), nullable=True),
    sa.Column('response_date', sa.DateTime(), nullable=True),
    sa.Column('response_hour', sa.String(), nullable=True),
    sa.Column('response_minute', sa.String(), nullable=True),
    sa.Column('response_expect', sa.DateTime(), nullable=True),
    sa.Column('response_content', sa.String(), nullable=True),
    sa.Column('response_remarks', sa.String(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('return_check', sa.String(), nullable=True),
    sa.Column('return_person', sa.String(), nullable=True),
    sa.Column('return_address', sa.String(), nullable=True),
    sa.Column('return_tel', sa.String(), nullable=True),
    sa.Column('return_manager', sa.String(), nullable=True),
    sa.Column('police_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('bundled_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_class_L', sa.String(), nullable=True),
    sa.Column('item_class_M', sa.String(), nullable=True),
    sa.Column('item_class_S', sa.String(), nullable=True),
    sa.Column('item_value', sa.Boolean(), nullable=True),
    sa.Column('item_feature', sa.String(), nullable=True),
    sa.Column('item_color', sa.String(), nullable=True),
    sa.Column('item_storage', sa.String(), nullable=True),
    sa.Column('item_storage_place', sa.String(), nullable=True),
    sa.Column('item_maker', sa.String(), nullable=True),
    sa.Column('item_expiration', sa.DateTime(), nullable=True),
    sa.Column('item_num', sa.Integer(), nullable=True),
    sa.Column('item_unit', sa.String(), nullable=True),
    sa.Column('item_plice', sa.String(), nullable=True),
    sa.Column('item_money', sa.String(), nullable=True),
    sa.Column('item_remarks', sa.String(), nullable=True),
    sa.Column('item_situation', sa.String(), nullable=True),
    sa.Column('lostitem_id', sa.Integer(), nullable=True),
    sa.Column('card_campany', sa.String(), nullable=True),
    sa.Column('card_tel', sa.String(), nullable=True),
    sa.Column('card_name', sa.String(), nullable=True),
    sa.Column('card_person', sa.String(), nullable=True),
    sa.Column('card_return', sa.DateTime(), nullable=True),
    sa.Column('card_item', sa.DateTime(), nullable=True),
    sa.Column('card_item_hour', sa.String(), nullable=True),
    sa.Column('card_item_minute', sa.String(), nullable=True),
    sa.Column('card_manager', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lostitem_id'], ['lost_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('denomination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten_thousand_yen', sa.Integer(), nullable=True),
    sa.Column('five_thousand_yen', sa.Integer(), nullable=True),
    sa.Column('two_thousand_yen', sa.Integer(), nullable=True),
    sa.Column('one_thousand_yen', sa.Integer(), nullable=True),
    sa.Column('five_hundred_yen', sa.Integer(), nullable=True),
    sa.Column('one_hundred_yen', sa.Integer(), nullable=True),
    sa.Column('fifty_yen', sa.Integer(), nullable=True),
    sa.Column('ten_yen', sa.Integer(), nullable=True),
    sa.Column('five_yen', sa.Integer(), nullable=True),
    sa.Column('one_yen', sa.Integer(), nullable=True),
    sa.Column('total_yen', sa.Integer(), nullable=True),
    sa.Column('item_situation', sa.String(), nullable=True),
    sa.Column('commemorative_coin_1', sa.String(), nullable=True),
    sa.Column('commemorative_coin_1_value', sa.String(), nullable=True),
    sa.Column('commemorative_coin_2', sa.String(), nullable=True),
    sa.Column('commemorative_coin_2_value', sa.String(), nullable=True),
    sa.Column('lostitem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lostitem_id'], ['lost_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('denomination')
    op.drop_table('bundled_item')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('lost_item')
    # ### end Alembic commands ###
